import { expect,test,type Page } from '@playwright/test';

async function connect(page:Page,setup=false){await page.goto('/?mock=1');if(setup)await page.getByLabel('First-time physical-presence setup').check();await page.getByLabel(/^Device secret/).fill('device-secret-123456');await page.getByRole('button',{name:setup?'Provision and connect':'Authenticate and connect'}).click();await expect(page.getByText(setup?'Setup complete. Device authenticated.':'Authenticated with device.')).toBeVisible()}
async function addProfile(page:Page){await page.getByRole('button',{name:'Profiles'}).click();await page.getByLabel('Profile ID').fill('bolts');await page.getByLabel('Part name').fill('M3 bolts');await page.getByLabel('Low-stock threshold').fill('8');await page.getByRole('button',{name:'Save profile'}).click();await expect(page.getByText('M3 bolts')).toBeVisible()}

test('first physical-presence setup and guided calibration',async({page})=>{await connect(page,true);await addProfile(page);await page.getByRole('button',{name:'Calibration'}).click();await page.getByRole('button',{name:'Tare empty bin'}).click();await page.getByLabel('Known piece count').fill('20');await page.getByLabel(/Known total sample mass/).fill('50');await page.getByRole('button',{name:'Calibrate known sample'}).click();await expect(page.getByText('Calibration recorded')).toBeVisible();await page.getByRole('button',{name:'Live count'}).click();await expect(page.getByText('Stable count')).toBeVisible();await expect(page.getByText('20',{exact:true})).toBeVisible()});

test('disconnect, reauthentication, sequence-gap refresh, fault and recovery never show a stale count',async({page})=>{await connect(page);await page.evaluate(()=>window.__partsTallyMock!.setState('stable',42));await expect(page.getByText('Stable count')).toBeVisible();await page.evaluate(()=>{window.__partsTallyMock!.setState('overload_indicated',null,false);window.__partsTallyMock!.reconnectWithGap()});await expect(page.getByText('Possible overload — no count')).toBeVisible();await expect(page.getByText(/Sequence gap detected/)).toBeVisible();await page.evaluate(()=>window.__partsTallyMock!.disconnect());await expect(page.getByText('Sensor disconnected — no count')).toBeVisible();await page.getByLabel(/^Device secret/).fill('device-secret-123456');await page.getByRole('button',{name:'Authenticate and connect'}).click();await expect(page.getByText('Possible overload — no count')).toBeVisible();await page.evaluate(()=>{window.__partsTallyMock!.setState('stable',41,false);window.__partsTallyMock!.reconnectWithGap()});await expect(page.getByText('Stable count')).toBeVisible()});

test('correction requires and preserves an audit reason',async({page})=>{await connect(page);await addProfile(page);await page.evaluate(()=>{window.__partsTallyMock!.addCount('bolts',41);window.__partsTallyMock!.reconnectWithGap()});await page.getByRole('button',{name:'History'}).click();await page.getByRole('button',{name:'Correct'}).click();await page.getByLabel('Correct count').fill('42');await expect(page.getByRole('button',{name:'Record correction'})).toBeVisible();await page.getByLabel('Audit reason').fill('manual recount');await page.getByRole('button',{name:'Record correction'}).click();await expect(page.getByText('manual recount')).toBeVisible()});

test('JSON/CSV export and validated preview before import apply',async({page})=>{await connect(page);await addProfile(page);await page.getByRole('button',{name:'Data'}).click();const json=page.waitForEvent('download');await page.getByRole('button',{name:'Export JSON backup'}).click();expect((await json).suggestedFilename()).toBe('parts-tally-backup-v3.json');const csv=page.waitForEvent('download');await page.getByRole('button',{name:'Export history CSV'}).click();expect((await csv).suggestedFilename()).toBe('parts-tally-history.csv');const backup={schemaVersion:3,deviceName:'Imported device',profiles:[],history:[]};await page.getByLabel('Choose JSON backup').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await expect(page.getByRole('heading',{name:'Import preview'})).toBeVisible();await page.getByRole('button',{name:'Apply this import'}).click();await expect(page.getByText(/Validated import applied/)).toBeVisible()});

test('incompatible schema is rejected before preview or apply',async({page})=>{await connect(page);await page.getByRole('button',{name:'Data'}).click();await page.getByLabel('Choose JSON backup').setInputFiles({name:'future.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schemaVersion:99,deviceName:'Future',profiles:[],history:[]}))});await expect(page.getByRole('alert')).toContainText('Incompatible backup');await expect(page.getByRole('button',{name:'Apply this import'})).toHaveCount(0)});
