import { render,screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,expect,it,vi } from 'vitest';
import App from '../App';
import { MockDeviceTransport } from '../protocol/mockTransport';

async function connect(mock=new MockDeviceTransport()){const user=userEvent.setup();render(<App transport={mock}/>);await user.type(screen.getByLabelText(/^Device secret/),'device-secret-123456');await user.click(screen.getByRole('button',{name:'Authenticate and connect'}));await screen.findByText(/Authenticated with device/);return {user,mock}}
describe('app workflows',()=>{
 it('authenticates without retaining the secret and distinguishes no-count state',async()=>{const {user}=await connect();expect(screen.getByText('Calibration required — no count')).toBeVisible();await user.click(screen.getByRole('button',{name:'Sign out'}));expect(screen.getByLabelText(/^Device secret/)).toHaveValue('')});
 it('creates a profile and completes guided calibration',async()=>{const {user}=await connect();await user.click(screen.getByRole('button',{name:'Profiles'}));await user.type(screen.getByLabelText('Profile ID'),'bolts');await user.type(screen.getByLabelText('Part name'),'M3 bolts');await user.click(screen.getByRole('button',{name:'Save profile'}));expect(await screen.findByText('M3 bolts')).toBeVisible();await user.click(screen.getByRole('button',{name:'Calibration'}));await user.click(screen.getByRole('button',{name:'Tare empty bin'}));await user.type(screen.getByLabelText('Known piece count'),'20');await user.type(screen.getByLabelText(/Known total sample mass/),'50');await user.click(screen.getByRole('button',{name:'Calibrate known sample'}));expect(await screen.findByText('Calibration recorded')).toBeVisible()});
 it('uses an explicit non-first active profile for threshold and calibration',async()=>{const mock=new MockDeviceTransport();await mock.createProfile({profileId:'first',name:'First profile',lowStockThreshold:0});await mock.createProfile({profileId:'active',name:'Active profile',lowStockThreshold:10});mock.snapshot.status.activeProfileId='active';mock.setState('stable',5,false);const {user}=await connect(mock);expect(screen.getByText(/Low stock: 5 is at or below the 10 threshold/)).toBeVisible();await user.click(screen.getByRole('button',{name:'Calibration'}));expect(screen.getByRole('heading',{name:'Guided calibration: Active profile'})).toBeVisible()});
 it('clears an expired import preview so apply cannot be retried',async()=>{const mock=new MockDeviceTransport();const apply=vi.spyOn(mock,'applyImport').mockRejectedValue(new Error('Import preview expired.'));const backup=await mock.exportData();const {user}=await connect(mock);await user.click(screen.getByRole('button',{name:'Data'}));await user.upload(screen.getByLabelText('Choose JSON backup'),new File([JSON.stringify(backup)],'backup.json',{type:'application/json'}));await user.click(await screen.findByRole('button',{name:'Apply this import'}));expect(await screen.findByRole('alert')).toHaveTextContent(/expired.*choose the JSON backup again/i);expect(screen.queryByRole('button',{name:'Apply this import'})).not.toBeInTheDocument();expect(apply).toHaveBeenCalledTimes(1)});
});
