import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { MeasurementStatus } from './status';
import { HttpDeviceTransport } from './protocol/httpTransport';
import { MockDeviceTransport } from './protocol/mockTransport';
import type { DeviceExport, DeviceSnapshot, DeviceTransport, ImportPreview, Profile } from './protocol/types';
import { ProtocolValidationError, validateExport } from './protocol/validation';
import { loadCache, saveCache } from './storage';

type ConnectionState='signed-out'|'connecting'|'connected'|'disconnected'|'authentication-failed'|'offline-cache';
const mock = import.meta.env.DEV && new URLSearchParams(location.search).has('mock');
const initialTransport = mock ? new MockDeviceTransport() : new HttpDeviceTransport();
if (mock) window.__partsTallyMock=initialTransport as MockDeviceTransport;

export default function App({transport=initialTransport}:{transport?:DeviceTransport}) {
 const cached=useMemo(()=>loadCache(),[]); const [connection,setConnection]=useState<ConnectionState>(cached?.snapshot?'offline-cache':'signed-out');
 const [snapshot,setSnapshot]=useState<DeviceSnapshot|undefined>(cached?.snapshot); const [notice,setNotice]=useState(cached?.snapshot?'Showing a browser-cached snapshot. Sign in for authoritative device data.':'');
 const [error,setError]=useState(''); const [baseUrl,setBaseUrl]=useState(cached?.baseUrl??'http://192.168.4.1'); const [deviceId,setDeviceId]=useState(cached?.deviceId??'pt-mock'); const [secret,setSecret]=useState(''); const [setup,setSetup]=useState(false);
 const [active,setActive]=useState('count'); const unsubscribe=useRef<(()=>void)|undefined>(undefined); const generation=useRef(0); const refreshSerial=useRef(0); const refreshBusy=useRef(false); const refreshTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined); const refreshQueued=useRef(false);
 const commit=(next:DeviceSnapshot,message='Device data refreshed.',epoch=generation.current)=>{if(epoch!==generation.current)return;const bounded={...next,history:next.history.slice(-100)};setSnapshot(bounded);setConnection('connected');setNotice(message);saveCache({baseUrl,deviceId,snapshot:{...bounded,cachedAt:new Date().toISOString()}})};
 const refresh=async(message?:string,epoch=generation.current)=>{const serial=++refreshSerial.current;const value=await transport.refresh();if(serial!==refreshSerial.current)return;commit(value,message,epoch)};
 const cancelPending=()=>{generation.current+=1;refreshSerial.current+=1;if(refreshTimer.current!==undefined)clearTimeout(refreshTimer.current);refreshTimer.current=undefined;refreshBusy.current=false;refreshQueued.current=false};
 const markDisconnected=(epoch:number)=>{if(epoch!==generation.current)return;cancelPending();setConnection('disconnected');setNotice('Connection lost. Counts are withheld until current device data is restored.')};
 const scheduleRefresh=(epoch:number)=>{if(epoch!==generation.current)return;if(refreshBusy.current){refreshQueued.current=true;return}refreshBusy.current=true;refreshTimer.current=setTimeout(async()=>{refreshTimer.current=undefined;try{await refresh('Live device update received.',epoch)}catch{markDisconnected(epoch)}finally{refreshBusy.current=false;if(refreshQueued.current&&epoch===generation.current){refreshQueued.current=false;scheduleRefresh(epoch)}}},1000)};
 useEffect(()=>()=>{cancelPending();unsubscribe.current?.()},[]);
 async function signIn(e:FormEvent<HTMLFormElement>){e.preventDefault();cancelPending();const epoch=generation.current;setConnection('connecting');setError('');try{const fd=new FormData(e.currentTarget);const common={baseUrl,deviceId,deviceSecret:secret};const next=setup?await transport.provision({...common,wifiSsid:String(fd.get('wifiSsid')),wifiPassword:String(fd.get('wifiPassword'))}):await transport.connect(common);if(epoch!==generation.current)return;commit(next,setup?'Setup complete. Device authenticated.':'Authenticated with device.',epoch);setSecret('');unsubscribe.current?.();unsubscribe.current=transport.subscribe(async event=>{if(epoch!==generation.current)return;if(event.payload.sequenceGap){if(refreshTimer.current!==undefined)clearTimeout(refreshTimer.current);refreshTimer.current=undefined;refreshQueued.current=false;refreshBusy.current=true;try{await refresh('Sequence gap detected; status, profiles, and history were refreshed.',epoch)}catch{markDisconnected(epoch)}finally{refreshBusy.current=false}}else{const eventState=event.payload.state;if(typeof eventState==='string'&&eventState!=='stable'&&NO_COUNT_STATES.has(eventState)){setSnapshot(current=>current?{...current,status:{...current.status,measurement:{...current.status.measurement,state:eventState as DeviceSnapshot['status']['measurement']['state'],stable:false,estimatedCount:null,uncertaintyPieces:null}}}:current)}scheduleRefresh(epoch)}},()=>markDisconnected(epoch));}catch(e){if(epoch!==generation.current)return;const message=messageOf(e);setError(message);setConnection(/auth|secret|401/i.test(message)?'authentication-failed':'disconnected')}}
 function signOut(){cancelPending();unsubscribe.current?.();setConnection(cached?.snapshot?'offline-cache':'signed-out');setNotice('Signed out. Authentication tokens and secrets are not stored.');setSecret('')}
 const profile=snapshot?.profiles.find(candidate=>candidate.id===snapshot.status.activeProfileId)??snapshot?.profiles[0];
 return <><a className="skip" href="#main">Skip to main content</a><header><div><span className="brand-icon" aria-hidden="true">▣</span><h1>Parts Tally</h1></div><p>Local device companion</p></header>
 <main id="main">
  <section className="connection card" aria-labelledby="connection-heading"><div className="section-heading"><div><p className="eyebrow">Connection</p><h2 id="connection-heading">{connectionLabel(connection)}</h2></div><span className={`pill ${connection}`}><span aria-hidden="true">{connection==='connected'?'●':'○'}</span> {connection.replaceAll('-',' ')}</span></div>
  {connection!=='connected'?<form onSubmit={signIn}><div className="form-grid"><label>Device address<input name="baseUrl" type="url" required value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} autoCapitalize="none"/></label><label>Device ID<input name="deviceId" required pattern="pt-[A-Za-z0-9-]+" value={deviceId} onChange={e=>setDeviceId(e.target.value)}/></label><label>Device secret<input name="deviceSecret" type="password" required minLength={16} value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="current-password"/><small>Used only to request a short-lived session; never saved.</small></label></div>
  <label className="check"><input type="checkbox" checked={setup} onChange={e=>setSetup(e.target.checked)}/> First-time physical-presence setup</label>{setup&&<fieldset><legend>Setup session</legend><p>Hold the device setup button at power-up. The app requests the temporary setup token directly; it is never stored. Leave both Wi-Fi fields blank for direct-only mode.</p><div className="form-grid"><label>Wi-Fi name (optional)<input name="wifiSsid" maxLength={32}/></label><label>Wi-Fi password (optional)<input name="wifiPassword" type="password" maxLength={63}/></label></div></fieldset>}<button className="primary" disabled={connection==='connecting'}>{connection==='connecting'?'Authenticating…':setup?'Provision and connect':'Authenticate and connect'}</button></form>:<div><p>Connected to <strong>{snapshot?.status.deviceName??snapshot?.status.deviceId}</strong>. Device data below is authoritative.</p><button onClick={signOut}>Sign out</button></div>}
  {error&&<p className="error" role="alert"><span aria-hidden="true">⚠ </span>{error}</p>}</section>
  {snapshot&&<><div className="live-region" aria-live="polite" aria-atomic="true">{notice}</div><nav aria-label="Device sections">{[['count','Live count'],['profiles','Profiles'],['calibration','Calibration'],['history','History'],['data','Data']].map(([id,label])=><button key={id} className={active===id?'active':''} aria-current={active===id?'page':undefined} onClick={()=>setActive(id)}>{label}</button>)}</nav>
   {active==='count'&&<section className="panel"><MeasurementStatus state={connection==='connected'?snapshot.status.measurement.state:'disconnected'} count={connection==='connected'?snapshot.status.measurement.estimatedCount:null} uncertainty={connection==='connected'?snapshot.status.measurement.uncertaintyPieces:null}/>{connection==='connected'&&snapshot.status.measurement.state==='stable'&&snapshot.status.measurement.estimatedCount!==null&&profile&&<p className={snapshot.status.measurement.estimatedCount<=profile.lowStockThreshold?'stock-alert':'stock-ok'} role="status"><span aria-hidden="true">{snapshot.status.measurement.estimatedCount<=profile.lowStockThreshold?'⚠':'✓'}</span> {snapshot.status.measurement.estimatedCount<=profile.lowStockThreshold?`Low stock: ${snapshot.status.measurement.estimatedCount} is at or below the ${profile.lowStockThreshold} threshold.`:`Stock above threshold: ${snapshot.status.measurement.estimatedCount} is above ${profile.lowStockThreshold}.`}</p>}{snapshot.status.faults.length>0&&<div className="fault" role="alert"><h3>Active device fault</h3><ul>{snapshot.status.faults.map(f=><li key={f}>{f.replaceAll('_',' ')}</li>)}</ul><p>Counts stay withheld until the device reports recovery. Do not rely on a cached value.</p></div>}<Safety/></section>}
   {active==='profiles'&&<Profiles snapshot={snapshot} transport={transport} refresh={refresh} enabled={connection==='connected'}/>}
   {active==='calibration'&&<Calibration profile={profile} transport={transport} refresh={refresh} enabled={connection==='connected'}/>}
   {active==='history'&&<History snapshot={snapshot} transport={transport} refresh={refresh} enabled={connection==='connected'}/>}
   {active==='data'&&<DataTools snapshot={snapshot} transport={transport} refresh={refresh} enabled={connection==='connected'}/>}
  </>}
 </main><footer><p>No account · No analytics · No cloud · Local network only</p></footer></>
}

function Profiles({snapshot,transport,refresh,enabled}:{snapshot:DeviceSnapshot;transport:DeviceTransport;refresh:(m?:string)=>Promise<void>;enabled:boolean}){const [editing,setEditing]=useState<Profile>();const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const id=String(f.get('profileId'));const input={name:String(f.get('name')).trim(),lowStockThreshold:Number(f.get('threshold'))};if(editing)await transport.updateProfile(editing.id,input);else await transport.createProfile({profileId:id,...input});setEditing(undefined);await refresh('Profile saved on the device.')};return <section className="panel" aria-labelledby="profiles-title"><h2 id="profiles-title">Device profiles and thresholds</h2><p>Profiles, calibration, and thresholds shown here are device-authoritative.</p><ul className="profile-list">{snapshot.profiles.map(p=><li key={p.id}><div><strong>{p.name}</strong><span>ID: {p.id} · Low stock at {p.lowStockThreshold} · {p.calibrated?'Calibrated':'Not calibrated'}</span></div><button disabled={!enabled} onClick={()=>setEditing(p)}>Edit</button></li>)}</ul><form key={editing?.id??'new'} onSubmit={submit}><h3>{editing?'Edit profile':'Add profile'}</h3><div className="form-grid"><label>Profile ID<input name="profileId" required pattern="[A-Za-z0-9_-]{1,64}" disabled={!!editing} defaultValue={editing?.id}/></label><label>Part name<input name="name" required maxLength={80} defaultValue={editing?.name}/></label><label>Low-stock threshold<input name="threshold" type="number" min="0" step="1" required defaultValue={editing?.lowStockThreshold??10}/></label></div><button className="primary" disabled={!enabled}>Save profile</button>{editing&&<button type="button" onClick={()=>setEditing(undefined)}>Cancel edit</button>}</form></section>}

function Calibration({profile,transport,refresh,enabled}:{profile?:Profile;transport:DeviceTransport;refresh:(m?:string)=>Promise<void>;enabled:boolean}){const [step,setStep]=useState(1);const [msg,setMsg]=useState('');if(!profile)return <section className="panel"><h2>Guided calibration</h2><p>Create a profile before calibration.</p></section>;async function tare(){await transport.tare(profile!.id);setStep(2);setMsg('Empty-bin tare saved. Add a known number of identical parts.')};async function calibrate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await transport.calibrate(profile!.id,Number(f.get('knownCount')),f.get('knownMass')?Number(f.get('knownMass')):undefined);setStep(3);setMsg('Known-count calibration saved on the device.');await refresh(msg)}return <section className="panel" aria-labelledby="calibration-title"><p className="eyebrow">Step {step} of 3</p><h2 id="calibration-title">Guided calibration: {profile.name}</h2><ol className="steps"><li className={step>=1?'current':''}>Empty bin tare</li><li className={step>=2?'current':''}>Known-count sample</li><li className={step>=3?'current':''}>Verify stable count</li></ol>{step===1&&<><h3>Place the empty bin on the platform</h3><p>Remove every part. Wait for the platform to settle. Keep below the rated load and never press on the PCB.</p><button className="primary" disabled={!enabled} onClick={tare}>Tare empty bin</button></>}{step===2&&<form onSubmit={calibrate}><h3>Add known, identical parts</h3><p>Use at least 10 pieces. Count them by hand before placing them in the bin.</p><div className="form-grid"><label>Known piece count<input name="knownCount" type="number" min="10" max="1000000" step="1" required/></label><label>Known total sample mass in grams (required for a fresh device)<input name="knownMass" type="number" min="0.001" step="any"/></label></div><button className="primary" disabled={!enabled}>Calibrate known sample</button></form>}{step===3&&<><h3>Calibration recorded</h3><p>Return to Live count and confirm the device reports a stable result with explicit uncertainty. Repeat calibration if uncertainty is excessive.</p></>}{msg&&<p role="status">{msg}</p>}</section>}

function History({snapshot,transport,refresh,enabled}:{snapshot:DeviceSnapshot;transport:DeviceTransport;refresh:(m?:string)=>Promise<void>;enabled:boolean}){const [selected,setSelected]=useState<string>();const [confirmation,setConfirmation]=useState('');const target=snapshot.history.find(h=>h.eventId===selected);async function correct(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await transport.correct(target!.eventId,target!.profileId,Number(f.get('count')),String(f.get('reason')).trim());setSelected(undefined);await refresh('Correction recorded with its audit reason.')}async function clear(){await transport.clearHistory('CLEAR HISTORY');setConfirmation('');await refresh('Device history cleared.')}return <section className="panel"><h2>Bounded device history</h2><p>The device retains up to 256 entries; this view and browser snapshot show the newest 100. Corrections append an audit event and do not rewrite the original.</p>{snapshot.history.length?<div className="table-scroll"><table><caption>Count and correction events</caption><thead><tr><th>Event</th><th>Profile</th><th>Count</th><th>Reason</th><th>Action</th></tr></thead><tbody>{snapshot.history.map(h=><tr key={h.eventId}><td>{h.kind}</td><td>{h.profileId}</td><td>{h.count}</td><td>{h.reason||'—'}</td><td>{h.kind==='count'?<button disabled={!enabled} onClick={()=>setSelected(h.eventId)}>Correct</button>:'Audit entry'}</td></tr>)}</tbody></table></div>:<p>No history entries.</p>}{target&&<form onSubmit={correct}><h3>Correct count {target.count}</h3><div className="form-grid"><label>Correct count<input name="count" type="number" min="0" max="100000000" step="1" required/></label><label>Audit reason<input name="reason" required minLength={1} maxLength={200}/></label></div><button className="primary">Record correction</button><button type="button" onClick={()=>setSelected(undefined)}>Cancel</button></form>}<details className="danger-zone"><summary>Clear device history</summary><p>This removes all device history and cannot be undone. Export a backup first.</p><label>Type CLEAR HISTORY<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button disabled={!enabled||confirmation!=='CLEAR HISTORY'} onClick={clear}>Clear history permanently</button></details></section>}

function DataTools({snapshot,transport,refresh,enabled}:{snapshot:DeviceSnapshot;transport:DeviceTransport;refresh:(m?:string)=>Promise<void>;enabled:boolean}){const [data,setData]=useState<DeviceExport>();const [preview,setPreview]=useState<ImportPreview>();const [error,setError]=useState('');async function jsonExport(){download(JSON.stringify(await transport.exportData(),null,2),'parts-tally-backup-v3.json','application/json')}function csv(){const q=(v:unknown)=>`"${String(v).replaceAll('"','""')}"`;download(['sequence,eventId,kind,profileId,count,reason,relatedEventId',...snapshot.history.map(h=>[h.sequence,h.eventId,h.kind,h.profileId,h.count,h.reason,h.relatedEventId??''].map(q).join(','))].join('\n'),'parts-tally-history.csv','text/csv')}async function choose(e:React.ChangeEvent<HTMLInputElement>){setPreview(undefined);setError('');try{const file=e.target.files?.[0];if(!file)return;const parsed=validateExport(JSON.parse(await file.text()));setData(parsed);setPreview(await transport.previewImport(parsed))}catch(e){setData(undefined);setError(messageOf(e))}}async function apply(){if(!data||!preview)return;try{await transport.applyImport(data,preview.previewToken)}catch(e){setPreview(undefined);setData(undefined);setError(`${messageOf(e)} Choose the JSON backup again to request a new preview.`);return}setPreview(undefined);setData(undefined);await refresh('Validated import applied to the device.')}return <section className="panel"><h2>Portable local data</h2><p>JSON backups contain device name, profiles, calibration, thresholds, and bounded history. CSV contains history only. Neither format includes Wi-Fi credentials, device secrets, session tokens, or browser settings.</p><div className="button-row"><button disabled={!enabled} onClick={jsonExport}>Export JSON backup</button><button onClick={csv}>Export history CSV</button></div><hr/><h3>Import JSON backup</h3><p>Selecting a file validates schema version 3 and forbidden secret fields, then requests a device preview. Nothing changes until you apply it.</p><label className="file">Choose JSON backup<input type="file" accept="application/json,.json" disabled={!enabled} onChange={choose}/></label>{error&&<p role="alert" className="error">{error}</p>}{preview&&<div className="preview" role="status"><h4>Import preview</h4><p>This operation replaces the device profile and history collections; it does not append records.</p><dl><div><dt>Profiles to replace</dt><dd>{preview.profilesToReplace}</dd></div><div><dt>History entries to replace</dt><dd>{preview.historyToReplace}</dd></div></dl><p>Preview expires in {preview.expiresInSeconds} seconds. The unchanged file and same authenticated session are required.</p><button className="primary" onClick={apply}>Apply this import</button><button onClick={()=>{setPreview(undefined);setData(undefined)}}>Cancel</button></div>}</section>}

function Safety(){return <aside className="safety"><h3>Measurement limits</h3><p>USB 5 V SELV only. Parts Tally is not a certified or legal-for-trade scale and is unsuitable for safety-critical decisions. Count uncertainty, part variation, vibration, creep, wiring faults, and overload can make results wrong. Never treat an explicit no-count or fault state as zero.</p></aside>}
const NO_COUNT_STATES=new Set(['uncalibrated','unstable','stale','disconnected','saturated','overload_indicated','below_tare','calibration_invalid','uncertainty_excessive']);
function connectionLabel(s:ConnectionState){return s==='connected'?'Device authenticated':s==='connecting'?'Authenticating…':s==='authentication-failed'?'Authentication failed':s==='offline-cache'?'Offline cached view':s==='disconnected'?'Device disconnected':'Connect to your device'}
function messageOf(e:unknown){return e instanceof ProtocolValidationError?e.message:e instanceof Error?e.message:'Unexpected device error.'}
function download(content:string,name:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
