[platformio]
default_envs = seeed_xiao_esp32c3

[env]
build_flags = -std=gnu++17 -Wall -Wextra -Werror
build_unflags = -std=gnu++11
check_skip_packages = yes
lib_deps =
  bblanchon/ArduinoJson@7.4.2

[env:seeed_xiao_esp32c3]
platform = espressif32@6.10.0
board = seeed_xiao_esp32c3
framework = arduino
lib_deps =
  ${env.lib_deps}
  links2004/WebSockets@2.7.1
platform_packages =
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.17
build_src_filter = +<*> -<native_main.cpp>

[env:native]
platform = native@1.2.1
test_framework = unity
lib_deps =
  ${env.lib_deps}
  throwtheswitch/Unity@2.6.1
build_src_filter = +<domain/> +<services/> +<protocol/> -<main.cpp> -<drivers/>
check_src_filters = +<src/domain/> +<src/services/> +<src/protocol/>
check_flags =
  cppcheck: --suppress=preprocessorErrorDirective:*ArduinoJson/Polyfills/preprocessor.hpp
test_build_src = yes
